# Generated by Django 4.0.10 on 2024-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxEmail',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('message_id', models.CharField(max_length=255)),
            ],
        ),
    ]
